---
# tasks file for install_fail2ban

- name: Include OS-specific tasks.
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure fail2ban is stated and enabled to start on boot.
  service:
    name: fail2ban
    state: started
    enabled: yes
