---
# RockyLinux tasks file for install_fail2ban

- name: Ensure the EPEL repository is installed.
  package:
    name: epel-release
    state: present
  when: software_install_fail2ban_epel_installed | bool

- name: Install fail2ban package.
  package:
    name: fail2ban
    state: present
    enablerepo: epel
