---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Ensure /var/log/auth.log exists
      copy:
        content: ""
        dest: /var/log/auth.log
        force: no
        group: root
        owner: root
        mode: 0600

  tasks:
    - name: "Include ansible-role-install_fail2ban"
      include_role:
        name: "ansible-role-install_fail2ban"
